### ISSUE TITLE
Just checking in

### ISSUE THREAD

**Issue by jenkoian** [szepeviktor/yoast-seo-test#1]
Just checking in on this and seeing what the latest is? We're integrating phpstan into our WP project and are near the point where we need to generate Yoast stubs. Is that what you're trying to do here, anything I can help out with?

Thanks!

**Comment by szepeviktor** [comment]
Hello @jenkoian !
Thank you for your issue!
Actually there is a GitHub org. for stubs https://github.com/php-stubs

Would you like to help dissecting the Yoast plugin?
https://github.com/php-stubs/wordpress-stubs/blob/master/finder.php

**Comment by szepeviktor** [comment]
btw do you know the [WordPress Extension](https://github.com/szepeviktor/phpstan-wordpress) for @phpstan?

**Comment by jenkoian** [comment]
Yep, already using those stubs and the extension :) 

I think what I need to do with regards Yoast is create the stubs (tried initially but fails on a bunch of dependencies and is a rabbit hole I didn't want to go down) then deal with some configuration stuff which I think is what you have as part of this repository? 

Thinking further, there's a bunch of other plugins I'll need to create stubs for (multilingualpress etc.). Do you think a kind of stubs directory for plugins is worth while? Is that what you were thinking also?

**Comment by szepeviktor** [comment]
> a kind of stubs directory for plugins

The https://github.com/php-stubs org. **is** a directory.
Just you have to release manually every version as plugin structure may change any time.

> is a rabbit hole I didn't want to go down

Come with me down this rabbit hole!
What plugin/code need the Yoast stubs?

**Comment by szepeviktor** [comment]
Looking at the Yoast plugin

```yaml
    "autoload": {
        "classmap": [
            "admin/",
            "frontend/",
            "inc/",
            "deprecated/",
            "cli/",
            "deprecated/",
            "vendor_prefixed/",
            "src/"
        ]
    },
```

I think admin and deprecated could be excluded.
What do you think?

**Comment by szepeviktor** [comment]
@jenkoian My first try: https://github.com/php-stubs/wordpress-seo-stubs
There **are** dependent packages.

**Comment by jenkoian** [comment]
Did not know you owned the @php-stubs org - nice! 

Will give your first try a go in a bit, just realised we're on the premium version, not sure if I specifically need stubs for the premium version though. Will let you know shortly.

What was your goal with @php-stubs then? Was it to essentially maintain a library of popular php libraries, plugins etc?

**Comment by szepeviktor** [comment]
> What was your goal with @php-stubs then? Was it to essentially maintain a library of popular php libraries, plugins etc?

While I've developed the PHPStan WordPress Extension WP-stubs were absolutely essentials as the core contains countless side-effect AND https://github.com/GiacoCorsiglia/wordpress-stubs is not updated anymore.

**Comment by szepeviktor** [comment]
Published on packagist: https://packagist.org/packages/php-stubs/wordpress-seo-stubs

**Comment by jenkoian** [comment]
Cool, thanks! Would love to pick your brains more on this phpstan stuff, is this the best place or is there a slack or anywhere you hang out?
